Updated Program Input Schema
9jacodeTech/eyen-iyak-be pull request #14
Opened 2023-10-28 16:06 UTC by genuineAB

## Changes Made

- Program controller, gateway, route, schema, interface, entities, and usecase were modified

## Useful Links

## How to test

-
-

## **Screenshots**
![image](https://github.com/9jacodeTech/eyen-iyak-be/assets/72891725/5c0c3669-7b24-42a2-abe9-a0adf1a9b650)

2023-11-10 13:34 UTC, chidioguejiofor commented on src/schemas/programs.ts
> +        donationLink: Joi.string().optional(),
why are these here

2023-11-10 13:34 UTC, chidioguejiofor commented on src/schemas/programs.ts
> +  program: Joi.string()
rename it to category

2023-11-10 13:34 UTC, chidioguejiofor commented on src/schemas/programs.ts
> +    .valid('artist development', 'cultural regeneration', 'education'),
`artist_development`, `cultural_regeneration`

2023-11-10 13:34 UTC, chidioguejiofor commented on src/schemas/programs.ts
> +    .min(1)
remove min

2023-11-10 13:34 UTC, chidioguejiofor commented on src/schemas/programs.ts
> +  sections: Joi.array()
subPrograms

2023-11-10 13:35 UTC, chidioguejiofor commented on src/schemas/programs.ts
> +        imageURL: Joi.array().items(Joi.string()).optional(),
imageURL should be a string.

2023-11-10 13:36 UTC, chidioguejiofor commented on src/schemas/programs.ts
> +        imageURL: Joi.array().items(Joi.string()).optional(),
required

2023-11-10 13:38 UTC, chidioguejiofor commented on src/schemas/programs.ts
> +      imageURL: Joi.array().items(Joi.string()).optional(),
background, 'white' |'gray'

2023-11-12 16:45 UTC, chidioguejiofor requested changes

2023-11-12 16:45 UTC, chidioguejiofor commented on src/entities.ts
> +  category: 'artist development' | 'cultural regeneration';
artist_development

2023-11-12 17:37 UTC, genuineAB commented on src/entities.ts
> +  category: 'artist development' | 'cultural regeneration';
Done

2023-11-12 17:59 UTC, chidioguejiofor approved these changes

2023-11-12 18:00 UTC, merged